# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22361353ce3055bd8431688415c0b757"
name = "ai-product-enhancer"
handle = "ai-product-enhancer-1"
application_url = "https://benefit-like-specifics-brad.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bc4fc407.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://benefit-like-specifics-brad.trycloudflare.com/auth/callback",
  "https://benefit-like-specifics-brad.trycloudflare.com/auth/shopify/callback",
  "https://benefit-like-specifics-brad.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
